### PR TITLE
Allow user to limit loaded data for a more responsive UI; save and restore window settings; reduce redundant work; accelerate rendering

### PR DESCRIPTION
**Pull request by adv12**
The main thrust of this PR is to add a bit of UI to MainForm that allows the user to specify a max number of rows and columns to load when processing an OptionsData object.

The UI is sort of ugly and probably sort of special case, so I hid it behind a user setting.

I added a Settings dialog to provide access to the setting.

Then there was only one setting in the Settings dialog, so I added an option to save and restore window state.

In the end, most of the changes are the additions to the Settings file and the inevitable rewriting of MainForm.Designer.cs by Visual Studio.  It looks like a lot got touched, but the net effect is very small.

### CODE REVIEW

**Comment by adv12** [comment]
I understand this project is sort of in maintenance mode and you may not be interested in this sort of change at this  point, but it would be good to hear that so I know how to proceed.  We have a modified version of the Visualizer internally based on old source, and I was tasked with syncing our changes with the latest release.  If you accept this PR, I have a couple more coming.  If this PR is likely to remain unmerged, I'll just merge it into my own develop branch, pull changes from yours, and consider my fork "truth" for my company.

**Comment by strhea** [comment]
Apologies for the delay. We usually collect and review PRs at our monthly technical committee meeting. Our next one is on Wednesday, Oct 25 @ 9am Central. I'll happily take a look at this. Would you be available to walk the group through your changes at the meeting?

**Comment by strhea** [comment]
If you don't already have the meeting invite. Send an email to Kimberly.Chauche@aggateway.org requesting to be added to invite for the ADAPT Technical Committee Meeting.

Quick question: Does your code reload the full dataset (as opposed to the limited set for visualization) when the CSVV export is triggered?

**Comment by adv12** [comment]
It does not, but I'd be happy to make that change.

**Comment by adv12** [comment]
I added a full reload of the data during CSV export as requested, but as I investigated the call chains through MainForm.ProcessData, I found all sorts of redundant reloading of data, especially via _tabPageSpatial_Paint.  I implemented checks to avoid reloading when requests have the same parameters as the last call.

I further observed that drawing large datasets was taking tens of seconds and fixed this by doing direct memory manipulation on a bitmap rather than making thousands of GDI+ calls.

**Comment by adv12** [comment]
For the meeting, should I plan to demo the changes, walk through the diffs line by line, or both?

**Comment by strhea** [comment]
Usually it is just a walk through the diff. I think everyone would be happy to see a demo if you want to do one.

**Pull request merged**
